services:
  - type: web
    name: sistema-examen
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app:app
    envVars:
      - key: MONGO_URI
        value: ""
      - key: DB_NAME
        value: "exam_system"
      - key: SECRET_KEY
        value: ""
      - key: EXAM_TIME
        value: "1800"
      - key: MAX_WARNINGS
        value: "3"
