questions = [
    {"question":"¿Qué es Python?","options":["Sistema operativo","Lenguaje de programación de alto nivel","Base de datos relacionales","Hardware"],"answer":"Lenguaje de programación de alto nivel"},
    {"question":"¿Por qué Python es fácil de aprender?","options":["por que tiene Sintaxis simple y parecida al lenguaje humano","Es compilado y usa constantes","No usa variables ni se tarda en compilar","Solo sirve online y no se importa librerias"],"answer":"por que tiene Sintaxis simple y parecida al lenguaje humano"},
    {"question":"¿Qué significa que Python sea interpretado?","options":["Que ejecuta el código línea por línea sin necesidad de compilarlo antes.","Compila primero y luego muestra resultados","No usa memoria para almacenar la informacion","Es un servidor local"],"answer":"Que ejecuta el código línea por línea sin necesidad de compilarlo antes."},
    {"question":"¿Qué es un programa?","options":["Es un conjunto de instrucciones que ejecuta una computadora.","Comentario que se realiza en las lineas","Lista con datos que indican informacion","Variable de salidas "],"answer":"Es un conjunto de instrucciones que ejecuta una computadora."},
    {"question":"¿Qué es un algoritmo?","options":["Es una secuencia ordenada de pasos para resolver un problema.","Error al momento de ejecutar un programa","Base de datos relacionales","Operador que se utiliza en las operaciones"],"answer":"Es una secuencia ordenada de pasos para resolver un problema."},
    {"question":"¿Qué es una variable?","options":["Es un espacio de memoria donde se almacena información.","Función que se reutiliza","Bucle que se repite","Texto donde se guarda datos"],"answer":"Es un espacio de memoria donde se almacena información."},
    {"question":"¿Qué es la sintaxis en python?","options":["Son las reglas que se deben seguir para escribir código correctamente.","Lista de codigos que se ejecutan","Función que realiza una variable","Variable que se almacena"],"answer":"Son las reglas que se deben seguir para escribir código correctamente."},
    {"question":"¿Qué es un dato entero?","options":["Es un número sin decimales.","Decimal ","Texto","Booleano"],"answer":"Es un número sin decimales."},
    {"question":"¿Qué es un dato float?","options":["Es un Número decimal","Número entero","Es una Cadena","Lista"],"answer":"Es un Número decimal"},
    {"question":"¿Qué es un dato str?","options":["Es una Cadena de texto","Es un Número","Es una Lista","Es un Booleano"],"answer":"Es una Cadena de texto"},
    {"question":"¿Qué es un dato bool?","options":["Es un valor logico Verdadero/Falso","Es un valor de Texto","Es un valor Decimal","Es un valor de una Lista"],"answer":"Es un valor logico Verdadero/Falso"},
    {"question":"Convertir datos significa:","options":["Cambiar un tipo de dato a otro.","Eliminar y guardar","Guardar y mostrar","Copiar y pegar"],"answer":"Cambiar un tipo de dato a otro."},
    {"question":"¿Qué función convierte texto a entero?","options":["int()","float()","str()","len()"],"answer":"int()"},
    {"question":"¿Qué función convierte texto a decimal?","options":["float()","int()","str()","type()"],"answer":"float()"},
    {"question":"¿Qué función convierte datos a texto?","options":["str()","int()","float()","input()"],"answer":"str()"},
    {"question":"¿Qué operador es aritmético?","options":["+","==","!=","<="],"answer":"+"},
    {"question":"¿Qué operador es relacional?","options":["==","+","*","/"],"answer":"=="},
    {"question":"¿Qué es una estructura condicional?","options":["Es una estructura que permite tomar decisiones.","Repetir las instrucciones","Guardar la informacion","Sumar los datos"],"answer":"Es una estructura que permite tomar decisiones."},
    {"question":"¿Qué palabra se usa para condición en Python?","options":["if","for","while","def"],"answer":"if"},
    {"question":"¿Qué significa else?","options":["Es la alternativa cuando la condición no se cumple.","Bucle que funciona cuando no hay alternativa","Función cuando no hay alternativa","Error cuando no se cumple"],"answer":"Es la alternativa cuando la condición no se cumple."},
    {"question":"¿Qué es un bucle?","options":["Es una estructura que repite instrucciones.","Variable repetitiva","Lista que se repite","Dato que no se cumple"],"answer":"Es una estructura que repite instrucciones."},
    {"question":"¿Qué hace el bucle for?","options":["Repite un bloque de código un número definido de veces","hace cumplir la Condición","Imprimir datos","Guardar informacion"],"answer":"Repite un bloque de código un número definido de veces."},
    {"question":"¿Qué hace el bucle while?","options":["Repite mientras una condición sea verdadera.","Suma los datos","Resta las variables","Importa los datos"],"answer":"Repite mientras una condición sea verdadera."},
    {"question":"¿Qué hace la función input()?","options":["Permite ingresar datos por teclado.","Mostrar datos","Guardar datos","Eliminar datos"],"answer":"Permite ingresar datos por teclado."},
    {"question":"¿Qué hace la funcion print()?","options":["Muestra información en pantalla.","Guardar informacion","Leer informacion","Copiar informacion"],"answer":"Muestra información en pantalla."},
    {"question":"¿Qué hace la funcion len()?","options":["Cuenta la cantidad de elementos o caracteres.","Imprime los elementos","Suma los elementos","Resta los elementos"],"answer":"Cuenta la cantidad de elementos o caracteres."},
    {"question":"¿Qué hace la funcion type()?","options":["Muestra el tipo de dato.","Cuenta los datos","Convierte el dato","Elimina el tipo de dato"],"answer":"Muestra el tipo de dato."},
    {"question":"¿Qué es una función?","options":["Es un Bloque de codigo reutilizable","Lista reutilizable","Bucle reutilizable","Variable reutilizable"],"answer":"Es un Bloque de codigo reutilizable"},
    {"question":"¿Cómo se define una función?","options":["con la palabra def","con el parametro if","con la palabrafor","con while"],"answer":"con la palabra def"},
    {"question":"¿Qué es un parámetro?","options":["Es un valor que recibe una función.","Lista","Error de codigo","Condición multiple"],"answer":"Es un valor que recibe una función."},
    {"question":"¿Qué hace return?","options":["Devuelve un resultado desde la función.","Imprime la funcion","Repite la funcion","Elimina la funcion"],"answer":"Devuelve un resultado desde la función."},
    {"question":"¿Qué es una lista?","options":["Es una colección ordenada y modificable de datos.","Colección fija ordenada","Número modificable","Texto ordenado"],"answer":"Es una colección ordenada y modificable de datos."},
    {"question":"¿Qué es una tupla?","options":["Es una colección ordenada e inmutable.","Lista mutable ordenada","Bucle inmutable","Función ordenada"],"answer":"Es una colección ordenada e inmutable."},
    {"question":"¿Qué es un diccionario?","options":["Es una colección de datos con clave y valor.","Lista con claves","Tupla de datos","Comentario en la coleccion"],"answer":"Es una colección de datos con clave y valor."},
    {"question":"¿Qué es un módulo?","options":["Es un archivo con funciones reutilizables.","Lista con archivos","Función utilizable","Bucle con funciones"],"answer":"Es un archivo con funciones reutilizables."},
    {"question":"¿Qué es una librería?","options":["Es un conjunto de módulos.","Lista con archivos","Variable con funciones","Comentario con modulos"],"answer":"Es un conjunto de módulos."},
    {"question":"¿Cómo importar una librería?","options":["Con la palabra import.","con using","include","con def"],"answer":"Con la palabra import."},
    {"question":"¿Qué es la indentación?","options":["Es el uso correcto de espacios para definir bloques.","Operador definido","Lista con espacios","Error"],"answer":"Es el uso correcto de espacios para definir bloques."},
    {"question":"¿Qué pasa si la indentación es incorrecta?","options":["Produce error.","no Funciona","no Mejora","no hace Nada"],"answer":"Produce error."},
    {"question":"¿Qué es un comentario?","options":["Es texto que Python ignora.","Código ignorado","Lista ignorada","Variable ignorada"],"answer":"Es texto que Python ignora."},
    {"question":"¿Cómo escribir un comentario?","options":["Con #","con //","con --","con /*"],"answer":"Con #"},
    {"question":"¿Qué error es común en principiantes?","options":["Olvidar paréntesis o mala indentación.","Variables","Funciones","Listas"],"answer":"Olvidar paréntesis o mala indentación."},
    {"question":"¿Qué permiten las estructuras repetitivas?","options":["Permiten ejecutar un conjunto de instrucciones varias veces automáticamente.","Guardar instrucciones","Borrar instrucciones","Comparar instrucciones"],"answer":"Permiten ejecutar un conjunto de instrucciones varias veces automáticamente."},
    {"question":"¿Qué ciclo se usa cuando sabemos cuántas veces repetir?","options":["Para","Mientras","Repetir","If"],"answer":"Para"},
    {"question":"¿Qué ciclo evalúa la condición antes de ejecutar?","options":["Mientras","Para","Repetir","If"],"answer":"Mientras"},
    {"question":"¿Qué ciclo siempre se ejecuta al menos una vez?","options":["Repetir","Mientras","Para","If"],"answer":"Repetir"},
    {"question":"¿Cuál es la sintaxis correcta de un ciclo Para?","options":["Para i <- inicio Hasta fin","While condición","If condición","Def función"],"answer":"Para i <- inicio Hasta fin"},
    {"question":"¿Qué pasa si no actualizamos la variable en un ciclo Mientras?","options":["Bucle infinito","Error","Nada","Se detiene"],"answer":"Bucle infinito"},
    {"question":"¿Qué ciclo es mejor para validar contraseñas?","options":["Repetir","Para","Mientras","If"],"answer":"Repetir"},
    {"question":"¿Qué estructura es ideal para tablas de multiplicar?","options":["Para","Mientras","Repetir","If"],"answer":"Para"}
]