questions = [
    {"question":"¿Qué es Python?","options":["Sistema operativo","Lenguaje de programación","Base de datos","Hardware"],"answer":"Lenguaje de programación"},
    {"question":"¿Por qué Python es fácil de aprender?","options":["Sintaxis simple","Es compilado","No usa variables","Solo sirve online"],"answer":"Sintaxis simple"},
    {"question":"¿Qué significa que Python sea interpretado?","options":["Ejecuta línea por línea","Compila primero","No usa memoria","Es un servidor"],"answer":"Ejecuta línea por línea"},
    {"question":"¿Qué es un programa?","options":["Conjunto de instrucciones","Comentario","Lista","Variable"],"answer":"Conjunto de instrucciones"},
    {"question":"¿Qué es un algoritmo?","options":["Secuencia de pasos","Error","Base de datos","Operador"],"answer":"Secuencia de pasos"},
    {"question":"¿Qué es una variable?","options":["Espacio de memoria","Función","Bucle","Texto"],"answer":"Espacio de memoria"},
    {"question":"¿Qué es la sintaxis?","options":["Reglas para escribir código","Lista","Función","Variable"],"answer":"Reglas para escribir código"},
    {"question":"¿Qué es int?","options":["Número entero","Decimal","Texto","Booleano"],"answer":"Número entero"},
    {"question":"¿Qué es float?","options":["Número decimal","Número entero","Cadena","Lista"],"answer":"Número decimal"},
    {"question":"¿Qué es str?","options":["Cadena de texto","Número","Lista","Booleano"],"answer":"Cadena de texto"},
    {"question":"¿Qué es bool?","options":["Verdadero/Falso","Texto","Decimal","Lista"],"answer":"Verdadero/Falso"},
    {"question":"Convertir datos significa:","options":["Cambiar tipo de dato","Eliminar","Guardar","Copiar"],"answer":"Cambiar tipo de dato"},
    {"question":"¿Qué función convierte texto a entero?","options":["int()","float()","str()","len()"],"answer":"int()"},
    {"question":"¿Qué función convierte texto a decimal?","options":["float()","int()","str()","type()"],"answer":"float()"},
    {"question":"¿Qué función convierte datos a texto?","options":["str()","int()","float()","input()"],"answer":"str()"},
    {"question":"¿Qué operador es aritmético?","options":["+","==","!=","<="],"answer":"+"},
    {"question":"¿Qué operador es relacional?","options":["==","+","*","/"],"answer":"=="},
    {"question":"¿Qué es estructura condicional?","options":["Tomar decisiones","Repetir","Guardar","Sumar"],"answer":"Tomar decisiones"},
    {"question":"Palabra para condición en Python","options":["if","for","while","def"],"answer":"if"},
    {"question":"¿Qué significa else?","options":["Alternativa","Bucle","Función","Error"],"answer":"Alternativa"},
    {"question":"¿Qué es un bucle?","options":["Repetición","Variable","Lista","Dato"],"answer":"Repetición"},
    {"question":"¿Qué hace for?","options":["Repetir veces definidas","Condición","Imprimir","Guardar"],"answer":"Repetir veces definidas"},
    {"question":"¿Qué hace while?","options":["Repite con condición","Suma","Resta","Importa"],"answer":"Repite con condición"},
    {"question":"¿Qué hace input()?","options":["Ingresar datos","Mostrar","Guardar","Eliminar"],"answer":"Ingresar datos"},
    {"question":"¿Qué hace print()?","options":["Mostrar información","Guardar","Leer","Copiar"],"answer":"Mostrar información"},
    {"question":"¿Qué hace len()?","options":["Cuenta elementos","Imprime","Suma","Resta"],"answer":"Cuenta elementos"},
    {"question":"¿Qué hace type()?","options":["Muestra tipo de dato","Cuenta","Convierte","Elimina"],"answer":"Muestra tipo de dato"},
    {"question":"¿Qué es una función?","options":["Bloque reutilizable","Lista","Bucle","Variable"],"answer":"Bloque reutilizable"},
    {"question":"¿Cómo se define una función?","options":["def","if","for","while"],"answer":"def"},
    {"question":"¿Qué es parámetro?","options":["Valor recibido","Lista","Error","Condición"],"answer":"Valor recibido"},
    {"question":"¿Qué hace return?","options":["Devuelve resultado","Imprime","Repite","Elimina"],"answer":"Devuelve resultado"},
    {"question":"¿Qué es lista?","options":["Colección modificable","Colección fija","Número","Texto"],"answer":"Colección modificable"},
    {"question":"¿Qué es tupla?","options":["Colección inmutable","Lista mutable","Bucle","Función"],"answer":"Colección inmutable"},
    {"question":"¿Qué es diccionario?","options":["Clave-valor","Lista","Tupla","Comentario"],"answer":"Clave-valor"},
    {"question":"¿Qué es módulo?","options":["Archivo reutilizable","Lista","Función","Bucle"],"answer":"Archivo reutilizable"},
    {"question":"¿Qué es librería?","options":["Conjunto de módulos","Lista","Variable","Comentario"],"answer":"Conjunto de módulos"},
    {"question":"¿Cómo importar librería?","options":["import","using","include","def"],"answer":"import"},
    {"question":"¿Qué es indentación?","options":["Espacios correctos","Operador","Lista","Error"],"answer":"Espacios correctos"},
    {"question":"¿Qué pasa con mala indentación?","options":["Error","Funciona","Mejora","Nada"],"answer":"Error"},
    {"question":"¿Qué es comentario?","options":["Texto ignorado","Código","Lista","Variable"],"answer":"Texto ignorado"},
    {"question":"¿Cómo escribir comentario?","options":["#","//","--","/*"],"answer":"#"},
    {"question":"Error común en principiantes","options":["Mala indentación","Variables","Funciones","Listas"],"answer":"Mala indentación"},
    {"question":"Estructuras repetitivas permiten","options":["Repetir instrucciones","Guardar","Borrar","Comparar"],"answer":"Repetir instrucciones"},
    {"question":"Ciclo cuando sabemos repeticiones","options":["Para","Mientras","Repetir","If"],"answer":"Para"},
    {"question":"Ciclo que evalúa antes","options":["Mientras","Para","Repetir","If"],"answer":"Mientras"},
    {"question":"Ciclo que ejecuta al menos una vez","options":["Repetir","Mientras","Para","If"],"answer":"Repetir"},
    {"question":"Sintaxis de ciclo Para","options":["Para i <- inicio Hasta fin","While condición","If condición","Def función"],"answer":"Para i <- inicio Hasta fin"},
    {"question":"Si no actualizamos while","options":["Bucle infinito","Error","Nada","Se detiene"],"answer":"Bucle infinito"},
    {"question":"Mejor ciclo para contraseñas","options":["Repetir","Para","Mientras","If"],"answer":"Repetir"},
    {"question":"Ideal para tabla de multiplicar","options":["Para","Mientras","Repetir","If"],"answer":"Para"}
]